
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TANGNO FIDEL
 */
public class ManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ManagerGUI
     */
    public ManagerGUI() {
        initComponents();
        table_update(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     Connection con1;
     PreparedStatement insert; 
     
   
     
 
 
         ////
    private void table_update() {
        int CC;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanagement","root","");
            insert = con1.prepareStatement("SELECT * FROM items;");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) stockleveltable.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
           
                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("ItemID"));
                    v2.add(Rs.getString("ItemName"));
                    v2.add(Rs.getString("Category"));
                    v2.add(Rs.getString("Price"));
                    v2.add(Rs.getString("StockLevel"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanagement","root","");
            insert = con1.prepareStatement("SELECT * FROM student");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable2.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
           
                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("id"));
                    v2.add(Rs.getString("name"));
                    v2.add(Rs.getString("studentid"));
                    v2.add(Rs.getString("cource"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanagement","root","");
            insert = con1.prepareStatement("SELECT * FROM sales;");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
           
                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("SaleID"));
                    v2.add(Rs.getString("ItemID"));
                    v2.add(Rs.getString("SaleDate"));
                    v2.add(Rs.getString("QuantitySold"));
                    v2.add(Rs.getString("TotalAmount"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventorymanagement","root","");
            insert = con1.prepareStatement("SELECT * FROM suppliers;");
            ResultSet Rs = insert.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable3.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
           
                for (int ii = 1; ii <= CC; ii++) {
                    v2.add(Rs.getString("SupplierID"));
                    v2.add(Rs.getString("SupplierName"));
                    v2.add(Rs.getString("ContactInfo"));
                    v2.add(Rs.getString("Address"));
                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JTabbedPane();
        stocklevel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        stockleveltablepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockleveltable = new javax.swing.JTable();
        stocklevelform = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        threshold = new javax.swing.JLabel();
        supplier = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        categoryjTextField15 = new javax.swing.JTextField();
        restock = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        restockform = new javax.swing.JPanel();
        idrestock = new javax.swing.JLabel();
        restockname = new javax.swing.JLabel();
        restockquantity = new javax.swing.JLabel();
        restockidjTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        restocktablepanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        sales = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        salesform = new javax.swing.JPanel();
        saleid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        salesquantity = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        salestablepanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deletesales = new javax.swing.JButton();
        updatesales = new javax.swing.JButton();
        createsale = new javax.swing.JButton();
        suppliers = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        itemname = new javax.swing.JPanel();
        itemid = new javax.swing.JLabel();
        itemsname = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        supplierstableform = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        createsale1 = new javax.swing.JButton();
        createsuppliers = new javax.swing.JButton();
        deletesuppliers = new javax.swing.JButton();
        updatesuppliers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPane.setBackground(new java.awt.Color(102, 255, 153));

        stocklevel.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);

        stockleveltablepanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 255, 102));

        stockleveltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Quantity", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stockleveltable);

        stockleveltablepanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(stockleveltablepanel);

        stocklevelform.setBackground(new java.awt.Color(153, 153, 255));

        Name.setText("Name");

        brand.setText("Brand");

        category.setText("Category");

        Price.setText("Price");

        threshold.setText("Threshold");

        supplier.setText("Supplier");

        submit.setBackground(new java.awt.Color(51, 255, 204));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stocklevelformLayout = new javax.swing.GroupLayout(stocklevelform);
        stocklevelform.setLayout(stocklevelformLayout);
        stocklevelformLayout.setHorizontalGroup(
            stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stocklevelformLayout.createSequentialGroup()
                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stocklevelformLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stocklevelformLayout.createSequentialGroup()
                                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(stocklevelformLayout.createSequentialGroup()
                                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(category, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(threshold, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                        .addComponent(supplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryjTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(stocklevelformLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(submit)))
                .addGap(0, 110, Short.MAX_VALUE))
        );
        stocklevelformLayout.setVerticalGroup(
            stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stocklevelformLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brand)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(category)
                    .addComponent(categoryjTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threshold)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(stocklevelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplier)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(submit)
                .addContainerGap(821, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(stocklevelform);

        stocklevel.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        mainPane.addTab("Stock Level", stocklevel);

        restock.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerLocation(300);

        restockform.setBackground(new java.awt.Color(204, 204, 255));

        idrestock.setText("ID");

        restockname.setText("Re-stock Name");

        restockquantity.setText("Restock Quantity");

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setText("Validate");

        javax.swing.GroupLayout restockformLayout = new javax.swing.GroupLayout(restockform);
        restockform.setLayout(restockformLayout);
        restockformLayout.setHorizontalGroup(
            restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockformLayout.createSequentialGroup()
                .addGroup(restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restockformLayout.createSequentialGroup()
                        .addGroup(restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(restockformLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(restockquantity)
                                    .addComponent(restockname))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restockformLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(idrestock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restockidjTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(restockformLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        restockformLayout.setVerticalGroup(
            restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restockformLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(restockidjTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idrestock))
                .addGap(37, 37, 37)
                .addGroup(restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restockname)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(restockformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restockquantity)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(861, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(restockform);

        restocktablepanel.setLayout(new java.awt.BorderLayout());

        jTable2.setForeground(new java.awt.Color(204, 153, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        restocktablepanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(restocktablepanel);

        restock.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        mainPane.addTab("Re-stock", restock);

        sales.setLayout(new java.awt.BorderLayout());

        jSplitPane3.setDividerLocation(300);

        salesform.setBackground(new java.awt.Color(204, 153, 255));

        saleid.setText("ID");

        jLabel2.setText("Name");

        salesquantity.setText("Quantity");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 204));
        jButton2.setText("Validate");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "SaleDate", "QuantitySold", "TotalAmount"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        deletesales.setText("Delete");

        updatesales.setText("Update");

        createsale.setText("Create");
        createsale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createsaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salestablepanelLayout = new javax.swing.GroupLayout(salestablepanel);
        salestablepanel.setLayout(salestablepanelLayout);
        salestablepanelLayout.setHorizontalGroup(
            salestablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salestablepanelLayout.createSequentialGroup()
                .addGroup(salestablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salestablepanelLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(createsale)
                        .addGap(103, 103, 103)
                        .addComponent(deletesales)
                        .addGap(104, 104, 104)
                        .addComponent(updatesales))
                    .addGroup(salestablepanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        salestablepanelLayout.setVerticalGroup(
            salestablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salestablepanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(salestablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletesales)
                    .addComponent(createsale)
                    .addComponent(updatesales))
                .addContainerGap(765, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout salesformLayout = new javax.swing.GroupLayout(salesform);
        salesform.setLayout(salesformLayout);
        salesformLayout.setHorizontalGroup(
            salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesformLayout.createSequentialGroup()
                .addGroup(salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salesformLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salesformLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(salesformLayout.createSequentialGroup()
                                .addComponent(saleid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(salesformLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton2))
                    .addGroup(salesformLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(salesquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salestablepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        salesformLayout.setVerticalGroup(
            salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesformLayout.createSequentialGroup()
                .addGroup(salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salesformLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleid)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(salesformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesquantity)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jButton2))
                    .addGroup(salesformLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salestablepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(salesform);

        sales.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        mainPane.addTab("Sales", sales);

        suppliers.setLayout(new java.awt.BorderLayout());

        jSplitPane4.setDividerLocation(300);

        itemname.setBackground(new java.awt.Color(102, 204, 255));

        itemid.setText("Item ID");

        itemsname.setText("Item Name");

        item.setText("item");

        jButton3.setBackground(new java.awt.Color(51, 255, 204));
        jButton3.setText("Confirm");

        javax.swing.GroupLayout itemnameLayout = new javax.swing.GroupLayout(itemname);
        itemname.setLayout(itemnameLayout);
        itemnameLayout.setHorizontalGroup(
            itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemnameLayout.createSequentialGroup()
                .addGroup(itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemnameLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(itemid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemsname, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(itemnameLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton3)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        itemnameLayout.setVerticalGroup(
            itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemnameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemid)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemsname)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(itemnameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addContainerGap(844, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(itemname);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        createsale1.setText("Create");

        createsuppliers.setText("Create");

        deletesuppliers.setText("Delete");

        updatesuppliers.setText("Update");

        javax.swing.GroupLayout supplierstableformLayout = new javax.swing.GroupLayout(supplierstableform);
        supplierstableform.setLayout(supplierstableformLayout);
        supplierstableformLayout.setHorizontalGroup(
            supplierstableformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierstableformLayout.createSequentialGroup()
                .addGroup(supplierstableformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supplierstableformLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(supplierstableformLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(createsuppliers)
                        .addGap(92, 92, 92)
                        .addComponent(updatesuppliers)
                        .addGap(97, 97, 97)
                        .addComponent(deletesuppliers)))
                .addContainerGap(577, Short.MAX_VALUE))
            .addGroup(supplierstableformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(supplierstableformLayout.createSequentialGroup()
                    .addGap(529, 529, 529)
                    .addComponent(createsale1)
                    .addContainerGap(594, Short.MAX_VALUE)))
        );
        supplierstableformLayout.setVerticalGroup(
            supplierstableformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierstableformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(supplierstableformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createsuppliers)
                    .addComponent(deletesuppliers)
                    .addComponent(updatesuppliers))
                .addContainerGap(712, Short.MAX_VALUE))
            .addGroup(supplierstableformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(supplierstableformLayout.createSequentialGroup()
                    .addGap(578, 578, 578)
                    .addComponent(createsale1)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );

        jSplitPane4.setRightComponent(supplierstableform);

        suppliers.add(jSplitPane4, java.awt.BorderLayout.CENTER);

        mainPane.addTab("Suppliers", suppliers);

        getContentPane().add(mainPane, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void createsaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createsaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createsaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel category;
    private javax.swing.JTextField categoryjTextField15;
    private javax.swing.JButton createsale;
    private javax.swing.JButton createsale1;
    private javax.swing.JButton createsuppliers;
    private javax.swing.JButton deletesales;
    private javax.swing.JButton deletesuppliers;
    private javax.swing.JLabel idrestock;
    private javax.swing.JLabel item;
    private javax.swing.JLabel itemid;
    private javax.swing.JPanel itemname;
    private javax.swing.JLabel itemsname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JPanel restock;
    private javax.swing.JPanel restockform;
    private javax.swing.JTextField restockidjTextField7;
    private javax.swing.JLabel restockname;
    private javax.swing.JLabel restockquantity;
    private javax.swing.JPanel restocktablepanel;
    private javax.swing.JLabel saleid;
    private javax.swing.JPanel sales;
    private javax.swing.JPanel salesform;
    private javax.swing.JLabel salesquantity;
    private javax.swing.JPanel salestablepanel;
    private javax.swing.JPanel stocklevel;
    private javax.swing.JPanel stocklevelform;
    private javax.swing.JTable stockleveltable;
    private javax.swing.JPanel stockleveltablepanel;
    private javax.swing.JButton submit;
    private javax.swing.JLabel supplier;
    private javax.swing.JPanel suppliers;
    private javax.swing.JPanel supplierstableform;
    private javax.swing.JLabel threshold;
    private javax.swing.JButton updatesales;
    private javax.swing.JButton updatesuppliers;
    // End of variables declaration//GEN-END:variables
}
